"""Interactive CLI for running the RAG pipeline with Qdrant-backed retrieval.

Milestone 4 — Rich terminal display:
  - Formatted separator bars and emoji section headers
  - Full source metadata + text preview for each retrieved chunk
  - Shows which provider/model generated the answer
  - Displays a warning if a fallback provider was used
"""

from __future__ import annotations

import os
import sys
import textwrap
from pathlib import Path

from dotenv import load_dotenv
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_qdrant import FastEmbedSparse, QdrantVectorStore, RetrievalMode

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

try:
    from src.rag_pipeline import answer_question
except ModuleNotFoundError:  # fallback for direct script execution
    from rag_pipeline import answer_question

load_dotenv()


# ── Display Helpers ───────────────────────────────────────────────────────────

BAR = "━" * 60


def _wrap(text: str, width: int = 72, indent: str = "   ") -> str:
    """Wrap text to terminal width with indentation for readability."""
    lines = text.split("\n")
    wrapped_lines: list[str] = []
    for line in lines:
        if line.strip() == "":
            wrapped_lines.append("")
        else:
            wrapped = textwrap.fill(line, width=width, subsequent_indent=indent)
            wrapped_lines.append(wrapped)
    return "\n".join(wrapped_lines)


def print_answer(result: dict) -> None:
    """Render the RAG result to the terminal in a rich, readable format."""
    answer: str = result["answer"]
    sources: list = result["sources"]
    provider_used: str = result.get("provider_used", "unknown")
    fallback_used: bool = result.get("fallback_used", False)

    # ── Fallback warning (shown before answer) ──────────────────────────────
    if fallback_used and provider_used != "none (all providers failed)":
        print(f"\n   Primary provider unavailable — using fallback: {provider_used}")

    # ── Answer block ────────────────────────────────────────────────────────
    print(f"\n{BAR}")
    print("   ANSWER")
    print(BAR)
    print()
    print(_wrap(answer))
    print()

    # ── Provider info ────────────────────────────────────────────────────────
    print(f"{BAR}")
    print(f"   Generated by: {provider_used}")
    print(BAR)

    # ── Sources block ────────────────────────────────────────────────────────
    if sources:
        print()
        print(f"{BAR}")
        print(f"   RETRIEVAL SOURCES  ({len(sources)} chunks)")
        print(BAR)

        for idx, doc in enumerate(sources, start=1):
            week = doc.metadata.get("week", "unknown")
            source_type = doc.metadata.get("source_type", "unknown")
            doc_id = doc.metadata.get("doc_id", "")

            # Truncate preview to ~300 chars, collapse newlines for readability
            preview = doc.page_content.strip().replace("\n", " ")
            if len(preview) > 300:
                preview = preview[:297] + "..."

            print(f"\n  [{idx}] Type: {source_type}  |  Week: {week}")
            if doc_id:
                print(f"       Doc ID: {doc_id}")
            print(f"       Preview: \"{preview}\"")

    print(f"\n{BAR}\n")


# ── Qdrant URL Normalisation ──────────────────────────────────────────────────

def normalize_qdrant_url(url: str) -> str:
    cleaned = url.strip()
    if not cleaned:
        return ""
    if cleaned.startswith("http://") or cleaned.startswith("https://"):
        if "/collections" in cleaned:
            cleaned = cleaned.split("/collections")[0]
        if cleaned.endswith("/api"):
            cleaned = cleaned[:-4]
        if cleaned.endswith("/v1"):
            cleaned = cleaned[:-3]
        if cleaned.endswith("/dashboard"):
            cleaned = cleaned[:-10]
        if cleaned.endswith("/"):
            cleaned = cleaned[:-1]
        if "cloud.qdrant.io" in cleaned and ":6333" not in cleaned:
            cleaned = f"{cleaned}:6333"
    return cleaned


# ── Setup ─────────────────────────────────────────────────────────────────────

QDRANT_URL = normalize_qdrant_url(os.getenv("QDRANT_URL", ""))
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
COLLECTION_NAME = "mlt_course_bot"

if not QDRANT_URL:
    raise ValueError("Missing QDRANT_URL in your .env file.")

print(f"\n{BAR}")
print("   MLT Course RAG Assistant — Starting Up")
print(BAR)
print("\n Loading embedding models (BAAI/bge-small-en-v1.5 + BM25)...")
dense_embeddings = FastEmbedEmbeddings(model_name="BAAI/bge-small-en-v1.5")
sparse_embeddings = FastEmbedSparse(model_name="Qdrant/bm25")

print(f" Connecting to Qdrant collection: '{COLLECTION_NAME}'...")
qdrant = QdrantVectorStore.from_existing_collection(
    embedding=dense_embeddings,
    sparse_embedding=sparse_embeddings,
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
    collection_name=COLLECTION_NAME,
    retrieval_mode=RetrievalMode.HYBRID,
)

# top_k=5 for richer context → better answers
retriever = qdrant.as_retriever(search_kwargs={"k": 5})

print(f"\n{BAR}")
print("   Ready!  Type your question below.")
print("   Tip: Ask about ML, AI, or any topic from the IIT Madras MLT course.")
print(f"   Type 'exit' or 'quit' to stop.\n{BAR}\n")


# ── Interactive Loop ──────────────────────────────────────────────────────────

while True:
    try:
        question = input(" Your question: ").strip()
    except (KeyboardInterrupt, EOFError):
        print("\n\nGoodbye! \n")
        break

    if not question:
        print("   (Please enter a question or type 'exit' to quit.)\n")
        continue

    if question.lower() in {"exit", "quit", "q"}:
        print("\nGoodbye! \n")
        break

    print("\n  Retrieving context and generating answer...\n")

    try:
        result = answer_question(question, retriever, top_k=5)
    except Exception as exc:
        print(f"\n  Pipeline error: {exc}\n")
        continue

    print_answer(result)
